name: FurnitureLib
version: 0.1
description: Experimental FurnitureLib
authors: [Ste3et_C0st, BeYkeRYkt]
website: http://dicecraft.de
depend: [ProtocolLib]
main: de.Ste3et_C0st.FurnitureLib.FurnitureLib